import { View, Text, SafeAreaView, FlatList } from 'react-native'
import React, { useEffect } from 'react'
import UnitContainer from '../../components/UnitContainer'
import ReturnHeader from '../../components/ReturnHeader'
import { useGlobalContext } from '../../context/GlobalProvider'
import { getChapters, getLoessons } from '../api/fetch'

const unitsList = [
  {
    unitId: 1,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: true,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 2,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 3,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 4,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 5,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 6,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 7,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 8,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 9,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 10,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
  {
    unitId: 11,
    name: "this is the first chapter",
    description: "this is the description of the chapter",
    objective: "this is the objective of the th chapter",
    isCurrent: false,
    isCompleted: false,
    lessons: [
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 1,
        passed: true,
        active: false,
        progress: 0,
        rating: 3,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 2,
        passed: true,
        active: false,
        progress: 0.3,
        rating: 2,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 3,
        passed: true,
        active: false,
        progress: 0,
        rating: 1,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 4,
        passed: false,
        active: true,
        progress: 0.4,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 5,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
      {
        name: "this is the lesson namne",
        description: "this is the lesson description",
        lessonId: 6,
        passed: false,
        active: false,
        progress: 0,
        rating: 0,
      },
    ]
  },
]

const chaptersMap = () => {
  const { units, curSkill, uiDevel } = useGlobalContext()

  return (
    <SafeAreaView className="w-full h-full flex-col items-center">
      <View className="w-full h-[10%]">
        <ReturnHeader title={curSkill.name} />
      </View>
      <FlatList
        data={uiDevel ? unitsList : units}
        keyExtractor={(item) => item.unitId}
        renderItem={({ item }) => (
          <UnitContainer
            unit={item}
          />
        )}
        className="w-full h-[90%]"
      />
    </SafeAreaView>
  )
}

export default chaptersMap