package com.enspd.mindyback.models;

public enum ScenarioType {
    RECOGNIZE_FACIAL_EXPRESSIONS,
    APPROPRIATE_REACTIONS,
    UNDERSTAND_EMOTIONS,
    COMMUNICATION_SKILLS,
    CONFLICT_RESOLUTION,
    GROUP_ACTIVITIES,
    DAILY_LIFE_SKILLS,
    SCHOOL_WORK_BEHAVIOR
}
